[MAIN]
SCALE_2X=1
SCR_WIDTH=1280
SCR_HEIGHT=960
WINDOWED=1
WINDOWED_FULLSCREEN=0
COLOUR_BITS=32
GRAPHICS_MODE=2

;F2_RES_DAT=f2_res.dat
;F2_RES_PATCHES=data

[MAINMENU]
; if set to 0 - main-menu image will display at its original size
; if set to 1 - main-menu image will stretch to fit the screen while maintaining its aspect ratio
; if set to 2 - main-menu image will stretch to fill the screen
MAIN_MENU_SIZE=2

; if set to 1 - hi-res main-menu graphics are used instead of original 'mainmenu.frm'
USE_HIRES_IMAGES=1

; if set to 1 - menu-buttons, text & text-background are scaled up for better visibility when using hi-res graphics
SCALE_BUTTONS_AND_TEXT_MENU=0

; When using a hi-res background, MENU_BG_OFFSET_X & MENU_BG_OFFSET_Y equal the
; distances in pixels from the top button to Menu Background Graphic edges
; For Fallout1 in Fallout2 engine mod, when using graphics from the Fallout1 Hi-Res patch
;MENU_BG_OFFSET_X=-24
;MENU_BG_OFFSET_Y=-24
; For Fallout 2
MENU_BG_OFFSET_X=-14
MENU_BG_OFFSET_Y=-4

[STATIC_SCREENS]
; if set to 0 - background image will display at its original size
; if set to 1 - background image will stretch to fit the screen while maintaining its aspect ratio
; if set to 2 - background image will stretch to fill the screen
DEATH_SCRN_SIZE=2
END_SLIDE_SIZE=2
HELP_SCRN_SIZE=2
SPLASH_SCRN_SIZE=2
